# https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#configure-all-key-value-pairs-in-a-configmap-as-container-environment-variables
kind: ConfigMap
apiVersion: v1
metadata:
  name: sirepo-alpha-configmap
  namespace: sirepo-alpha
  labels:
    app: sirepo-alpha
data:
  PYKERN_PKCONFIG_CHANNEL: 'alpha'
  PYKERN_PKDEBUG_REDIRECT_LOGGING: '1'
  PYKERN_PKDEBUG_WANT_PID_TIME: '1'
  PYTHONUNBUFFERED: '1'
  SIREPO_AUTH_METHODS: 'guest'
  SIREPO_COOKIE_HTTP_NAME: 'sirepo_alpha'
  SIREPO_FEATURE_CONFIG_UI_WEBSOCKET: '1'
  # TODO(e-carlin): how should this work in k8s?
  SIREPO_JOB_API_SUPERVISOR_URI: 'http://127.0.0.1:7100'
  SIREPO_JOB_DRIVER_MODULES: 'local'
  SIREPO_JOB_MAX_MESSAGE_BYTES: '200m'
  SIREPO_JOB_VERIFY_TLS: '1'
  SIREPO_PKCLI_JOB_SUPERVISOR_IP: '127.0.0.1'
  SIREPO_PKCLI_JOB_SUPERVISOR_PORT: '7100'
  # TODO(e-carlin): Should this be 127.0.0.1?
  SIREPO_PKCLI_SERVICE_IP: '0.0.0.0'
  # POSIT: matches deployment containerPort
  SIREPO_PKCLI_SERVICE_PORT: '8000'
  SIREPO_PKCLI_SERVICE_PROCESSES: '1'
  SIREPO_PKCLI_SERVICE_RUN_DIR: '/srv/sirepo'
  SIREPO_PKCLI_SERVICE_TORNADO: '1'
  SIREPO_SRDB_ROOT: '/srv/sirepo/db'
  TZ: '/etc/localtime'
