#!/bin/bash
export 'PYKERN_PKCONFIG_CHANNEL=alpha'
export 'PYKERN_PKDEBUG_REDIRECT_LOGGING=1'
export 'PYKERN_PKDEBUG_WANT_PID_TIME=1'
export 'PYTHONUNBUFFERED=1'
export 'SIREPO_AUTH_METHODS=guest'
export 'SIREPO_COOKIE_HTTP_NAME=sirepo_alpha'
export 'SIREPO_FEATURE_CONFIG_UI_WEBSOCKET=1'
export 'SIREPO_FEATURE_CONFIG_TRUST_SH_ENV=1'
export 'SIREPO_FEATURE_CONFIG_UI_WEBSOCKET=1'
export 'SIREPO_FEATURE_CONFIG_SIM_TYPES=elegant:genesis:impactt:srw'
export 'SIREPO_JOB_API_SUPERVISOR_URI=http://job-supervisor:8100'
export 'SIREPO_JOB_DRIVER_LOCAL_SUPERVISOR_URI=http://job-supervisor:8100'
export 'SIREPO_JOB_DRIVER_MODULES=local'
export 'SIREPO_JOB_MAX_MESSAGE_BYTES=200m'
export 'SIREPO_JOB_VERIFY_TLS=1'
export 'SIREPO_PKCLI_JOB_SUPERVISOR_IP=0.0.0.0'
export 'SIREPO_PKCLI_JOB_SUPERVISOR_PORT=8100'
export 'SIREPO_PKCLI_SERVICE_IP=0.0.0.0'
# POSIT: matches deployment containerPort
export 'SIREPO_PKCLI_SERVICE_PORT=8000'
export 'SIREPO_PKCLI_SERVICE_PROCESSES=1'
export 'SIREPO_PKCLI_SERVICE_RUN_DIR=/srv/sirepo'
export 'SIREPO_PKCLI_SERVICE_TORNADO=1'
# TODO(e-carlin): Just to get around configuring server, user, and password while we figure out email @SLAC
export 'SIREPO_SMTP_SEND_DIRECTLY=1'
export 'SIREPO_SRDB_ROOT=/srv/sirepo/db'
export 'TZ=/etc/localtime'
