apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    # Copied from mlflow-ui
    # TODO(e-carlin): How should this be kept in sync across all services?
    nginx.ingress.kubernetes.io/whitelist-source-range: 71.198.255.25,134.79.0.0/16,172.16.0.0/12,208.45.173.162,216.46.165.69,71.198.254.69
  name: sirepo
  namespace: sirepo-alpha
  labels:
    app: sirepo-alpha
spec:
  ingressClassName: nginx
  rules:
  - host: sirepo-alpha.slac.stanford.edu
    http:
      paths:
      - backend:
          service:
            name: api-server
            port:
              # TODO(e-carlin): Can I use named port sirepo-port?
              number: 8000
        path: /
        pathType: Prefix
