apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-supervisor
  namespace: sirepo-alpha
  labels:
    app: sirepo-alpha
    deployment: sirepo-alpha-job-supervisor
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: sirepo-alpha-job-supervisor
  template:
    metadata:
      labels:
        app: sirepo-alpha
        deployment: sirepo-alpha-job-supervisor
    spec:
      containers:
        - name: job-supervisor
          image: radiasoft/sirepo:20240903.204953
          command: ["/bin/bash", "/srv/sirepo_job_supervisor/cmd"]
          env:
            - name: SLACTWIN_GLOBAL_RESOURCES_SLACTWIN_DB_API_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: slactwin-config-db-api-auth-secret
                  key: slactwin-config-db-api-auth-secret
            - name: SIREPO_COOKIE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: sirepo-cookie-private-key
                  key: sirepo-cookie-private-key
            - name: SIREPO_JOB_SERVER_SECRET
              valueFrom:
                secretKeyRef:
                  name: sirepo-job-server-secret
                  key: sirepo-job-server-secret
          resources:
            requests:
              memory: "32Gi"
              cpu: "16"
            limits:
              memory: "32Gi"
              cpu: "16"
          volumeMounts:
            - mountPath: /srv
              name: storage
              subPath: sw/lume/radiasoft/sirepo-alpha/srv
      securityContext:
        runAsUser: 46588 # TODO(e-carlin): Need service user.
        runAsGroup: 1126 # TODO(e-carlin): Need service group.
        fsGroup: 1126 # TODO(e-carlin): Understand this better
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: pvc
