apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-supervisor
  namespace: sirepo-alpha
  labels:
    app: sirepo-alpha
    deployment: sirepo-alpha-job-supervisor
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: sirepo-alpha-job-supervisor
  template:
    metadata:
      labels:
        app: sirepo-alpha
        deployment: sirepo-alpha-job-supervisor
    spec:
      containers:
        - name: job-supervisor
          image: radiasoft/sirepo:20240903.204953
          command: ["/bin/bash", "/srv/sirepo_job_supervisor/cmd"]
          env:
            - name: SIREPO_COOKIE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: sirepo-cookie-private-key
                  key: sirepo-cookie-private-key
            - name: SIREPO_JOB_SERVER_SECRET
              valueFrom:
                secretKeyRef:
                  name: sirepo-job-server-secret
                  key: sirepo-job-server-secret
          # TODO(e-carlin): for things like nersc we will need to know this so agents can call back in.
          # For now, ignore.
          # ports:
          #   # Limited to 15 chars
          #   - name: supervisor-port
          #     containerPort: 8000
          # TODO(e-carlin): Tune these resource limits. Do so in conjuction with $SIREPO_JOB_DRIVER_LOCAL_*
          resources:
            requests:
              memory: "16Gi"
              cpu: "16"
            limits:
              memory: "16Gi"
              cpu: "16"
          volumeMounts:
            - mountPath: /srv
              name: storage
      securityContext:
        runAsUser: 46588 # TODO(e-carlin): this is my id. Get a service user?
        runAsGroup: 1126 # TODO(e-carlin): this is just the only group I'm in. Get a group?
        fsGroup: 1126 # TODO(e-carlin): Understand this better
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: pvc
