kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc
  namespace: sirepo-alpha
  labels:
    app: sirepo-alpha
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: sdf-group-ad
