apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg
  namespace: sirepo-alpha
  labels:
    app: sirepo-alpha
    deployment: sirepo-alpha-pg
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: sirepo-alpha-pg
  template:
    metadata:
      labels:
        app: sirepo-alpha
        deployment: sirepo-alpha-pg
    spec:
      containers:
        - name: pg
          image: postgres:16
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-password
                  key: pg-password
          envFrom:
            - configMapRef:
                name: pg
          resources:
            requests:
              memory: "16Gi"
              cpu: "8"
            limits:
              memory: "16Gi"
              cpu: "8"
          volumeMounts:
            - mountPath: /srv
              name: storage
              subPath: sw/lume/radiasoft/sirepo-alpha/srv
      securityContext:
        runAsUser: 46588 # TODO(e-carlin): Need service user.
        runAsGroup: 1126 # TODO(e-carlin): Need service group.
        fsGroup: 1126 # TODO(e-carlin): Understand this better
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: pvc
